### ISSUE TITLE
burntool_py report IndexError: list index out of range in line 44 【 if relydata[4] == 0: 】

### ISSUE THREAD

**Issue by ClayStan404** [milkv-duo/duo-arduino#21]
OS: Arch Linux
Arduino version: 2.3.4
board: Duo256
Python Verion: 3.12
pyserial Version : python-pyserial 3.5-6 installed by pacman from archlinux repo

When i run and upload examples 01.basics blink demo,it will raise a error:

/home/claystan/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: /home/claystan/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d/libc_nano.a(libc_a-signalr.o): in function `_getpid_r':
(.text._getpid_r+0x0): warning: _getpid is not implemented and will always fail
/home/claystan/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: /home/claystan/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d/libc_nano.a(libc_a-signalr.o): in function `.L0 ':
(.text._kill_r+0x20): warning: _kill is not implemented and will always fail

burntool.py v0.3

upload firmware /home/claystan/.cache/arduino/sketches/2DB384CBC1B074DFF6533C2B195A747E/Blink.ino.elf

start upload...

communication and testing...
Exception in thread Thread-1 (recv_date):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/claystan/.arduino15/packages/sophgo/tools/burntool_py/0.3/burntool.py", line 44, in recv_date
    if relydata[4] == 0:
       ~~~~~~~~^^^
IndexError: list index out of range
connect failed...
![截图 2024-12-14 17-53-49](https://github.com/user-attachments/assets/cd8140b3-9d58-4581-8753-b6e8d88f8c92)

**Comment by ClayStan404** [comment]
just found that i use v2 img without arduino support
waiting for this PR merge : https://github.com/milkv-duo/duo-buildroot-sdk-v2/pull/17
